<a href="https://colab.research.google.com/github/gabryel-silva/estudos-python/blob/main/revisao_prova_a2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### ***Declaração de varíaveis***

Variáveis são posições da memória reservada para armazenar um determiando valor, que tem um nome específico associado a cada
variável. No caso específico do Python, o nome da variável deve atender às seguintes regras:

* Começar com letra ou underline;
* Se for um nome composto, não pode conter espaço em branco;
* Os nomes são “case sensitive”;
* Use nomes que sejam auto-explicativos.

##### Declaração implícita

No python você não precisa definir o tipo de uma variável, que podem ser em geral do tipo: string, integer e float. Basta atribuir um valor a uma variável, depois, se quiser, podemos saber o tipo do dado armazenado usando type.

In [ ]:
print('Saída:')
var_nome = 'Gabryel'
print(var_nome)

Saída:
Gabryel


#### ***Entrada e saída de dados***

Podemos utilizar duas funções simples para entrada e saída de dados: `input( )` e `print( )`.
`variável = input(“texto”)`

Onde:
* variável = nome da variável que irá receber o valor lido
* “texto” é a pergunta que você pode fazer ao usuário
`print("texto {} texto{}".format(variável1,variável2))`

Onde:
* texto é parte da informação que você quer mostrar na tela
* `{}` é o local do texto onde você quer inserir um valor
* `format()` é uma função que converte o valor para uma representação formatada

A entrada de dados com input será sempre lida como um string.

##### Exemplo:

In [ ]:
print("Entrada e Saída: ")

var_nome = input('Qual é o seu nome?')
print("Meu nome é {}".format(var_nome))

# ou print(f"Meu nome é {var_nome}")
print(type(var_nome))

Entrada e Saída: 
Qual é o seu nome?Gabryel
Meu nome é Gabryel
<class 'str'>


#### ***Casting***

É a operação que muda um valor de um tipo para outro. Por exemplo, sabemos que a entrada da função input retorna sempre um string. Se quisermos converter de string para inteiro, devemos usar o casting.

##### Exemplo:

In [ ]:
print("Entrada e Saída: ")

var_idade = input("Qual é a sua idade?")

#Antes da conversão
print(type(var_idade))

#Após a conversão
print(type(int(var_idade)))

Entrada e Saída: 
Qual é a sua idade?22
<class 'str'>
<class 'int'>


## **Numpay**

Segundo o site https://numpy.org/, o NumPy é o pacote fundamental para a computação científica com Python. Ele contém entre outras coisas:

* um poderoso **objeto de matriz N-dimensional**;
* funções sofisticadas (transmissão);
* ferramentas para integrar códigos escritos em **C / C ++ e Fortran**;
* recursos úteis de álgebra linear, transformação de Fourier e números aleatórios.

Além de seus óbvios usos científicos, o NumPy também pode ser usado como um eficiente recipiente multidimensional de dados genéricos. Tipos de dados arbitrários podem ser definidos. Isso permite que o NumPy se integre de maneira fácil e rápida a uma ampla variedade de bancos de dados. O NumPy é licenciado sob a licença BSD , permitindo a reutilização com poucas restrições. Compreender o uso do NumPy pode ajudar a usar ferramentas de análise de dados como o Pandas, cujas principais operações são as seguintes operações, por exemplo:

    1.1. remoção e limpeza de dados;
    1.2. subconjunto e filtragem;
    1.3. transformação;
    1.4. classificação, únicas e definidas;
    1.5. estatísticas descritivas eficientes e agregação;
    1.6. mesclar e unir conjuntos de dados heterogêneos.


#### ***Instalação do NumPy***
Certifique-se que o NumPy está disponível em seu ambiente de desenvolvimento. No caso do Anaconda, na
interface do Anaconda Navigator, selecione Environments no menu lateral esquerdo. E certifique-se que o NumPy
está instalado.

#### ***Começando a usar NumPy***
Usaremos a convenção **`import numpy as np`**, de modo que você precisa apenas incluir np. antes do nome do
método.

#### ***Array***

Em Python podemos usar tanto Listas quanto Arrays para armazenar dados, e ambos podem ser indexados e
iterados. Os arrays precisam ser declaradas, enquanto as listas não precisam, pois fazem parte da sintaxe nativa
do Python. Portanto, as listas são mais usadas que os arrays. Entretanto, se precisar executar alguma função
aritmética deve utilizar arrays.

In [3]:
import numpy as np

print("Saída: ")

listCitys = ['Brasília','Goiânia','Belo horizonte']
print(listCitys)

Saída: 
['Brasília', 'Goiânia', 'Belo horizonte']


#### ***Principais funções com arrays***
Um ndarray é um contêiner multidimensional genérico para dados homogêneos, ou seja, todos os elementos devem ser do mesmo tipo.

* ***`array( )`***: converte dados de entrada (lista, tupla, array ou outro tipo de sequência) em um ndarray;

* ***`arange( )`***: como o intervalo interno, mas retorna um ndarray em vez de uma lista;

* ***`Ones( )`***: produza uma matriz de todos os 1s com a forma e o tipo especificados. Já a função ones_like leva outra array e produz um array ones da mesma forma e tipo;

* ***`Zeros( )`***: produz arrays de zer;

* ***`Empty()`***: produz um array vazio, não necessariamente com zeros.


##### **Exemplos:**

In [6]:
import numpy as np

print("Saída: ")

dados = [3,5,7,9]
print(f"\n Dados = {dados}")

array = np.array(dados)
print(f"\n Array = {array}")

var_arange = np.arange(10)
print(f"\n Arange = {var_arange}")

var_ones = np.ones((2,2))
print(f"\n Ones = {var_ones}")

var_zerosX = np.zeros((10))
print(f"\n Zeros = {var_zerosX}")

var_zerosM = np.zeros((2,3))
print(f"\n Zeros = {var_zerosM}")

var_empty = np.empty((2,3))
print(f"\n Empty = {var_empty}")

Saída: 

 Dados = [3, 5, 7, 9]

 Array = [3 5 7 9]

 Arange = [0 1 2 3 4 5 6 7 8 9]

 Ones = [[1. 1.]
 [1. 1.]]

 Zeros = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 Zeros = [[0. 0. 0.]
 [0. 0. 0.]]

 Empty = [[0. 0. 0.]
 [0. 0. 0.]]


#### ***Operações com arrays***
Outra vantagem do array é poder realizar operações em lote com os dados, sem precisar utilizar um loop,
também conhecido com vetorização. Inclusive muitas operações simples como **`sqrt`** ou **`exp`**.

In [10]:
import numpy as np

print("Saída: ")

a1 = np.array([[1,2,3],[4,5,6]])
print(f"\n Array1 = {a1}")

a2 = np.ones((2,3))
print(f"\n Array2 = {a2}")

var_sum = a1+a2
print(f"\n Array1 + Array2 = {var_sum}")

var_exp = a1**a2
print(f"\n Array1 elevado a 2 {var_exp}")

var_sub = a1-a2
print(f"\n Arra1 - Array2 = {var_sub}")

Saída: 

 Array1 = [[1 2 3]
 [4 5 6]]

 Array2 = [[1. 1. 1.]
 [1. 1. 1.]]

 Array1 + Array2 = [[2. 3. 4.]
 [5. 6. 7.]]

 Array1 elevado a 2 [[1. 2. 3.]
 [4. 5. 6.]]

 Arra1 - Array2 = [[0. 1. 2.]
 [3. 4. 5.]]


#### ***Outras operações com arrays***
Observe que existe uma importante diferença entre lista e arrays. Fatias de um array são visualizações do array original. Portanto, os dados não são copiados e quaisquer modificações na exibição serão refletidas no array original.

In [12]:
print("Saída: ")

myList = [3,4,5,7]
print(f"\n Lista = {myList}")

outList = myList[1:3]
print(f"\n Parte da lista = {outList}")

outList[1] = 23
print(f"\n modifica a parte da lista = {outList}")

print(f"\n Voltando à lista original = {myList}")

Saída: 

 Lista = [3, 4, 5, 7]

 Parte da lista = [4, 5]

 modifica a parte da lista = [4, 23]

 Voltando à lista original = [3, 4, 5, 7]
